### ISSUE TITLE
Turn of AUTH?

### ISSUE THREAD

**Issue by bartagergely** [m0wer/tiddlywiki-docker#3]
Is there a way to turn off BASIC AUTH completely?
I want the authentication on the reverse-proxy located 'in front of' the tiddlywiki.
Thank you!

**Comment by virgil9306** [comment]
just make your own edit to the script and remove the references to `USERNAME` and `PASSWORD`

**Comment by virgil9306** [comment]
Inside `init-and-run-wiki` there is a line at the end that says `exec /usr/bin/env node ...` -- just remove the `USERNAME` and `PASSWORD` parts

**Comment by ghost** [comment]
Sorry, where is `init-and-run-wiki`?

**Comment by nikolaus-stahlberg** [comment]
> Sorry, where is `init-and-run-wiki`?

Its one of the files in this repo. It is referenced by the `Dockerfile`.

Therefore to make the changes mentioned by @virgil9306 one needs to clone this repo, edit the `init-and-run-wiki` file accordingly and build the docker image locally by running `# docker build <directory_of_Dockerfile>`

**Comment by thedeany** [comment]
Alternatively, you could `docker exec -it YOUR_CONTAINER /bin/sh` and then `cd /usr/local/bin` and `vi init-and-run-wiki` to edit the file in place, removing the `username` and `password` options. This will survive a container restart but probably not a recreation. But this is an alternative to building the image yourself.

**Comment by m0wer** [comment]
First of all, sorry for the late reply. I didn't get any notifications since the repo is a fork and it was unwatched by default.

Now authentication is off unless the `USERNAME` environment variable is set.
