### ISSUE TITLE
Is this image compatible with raspberry pi?

### ISSUE THREAD

**Issue by ghost** [m0wer/tiddlywiki-docker#5]
Hi,

I just did test on virtual machine with ubuntu server, I managed to create and start container and access it via web without any issues. I repeated the same workflow on raspberry pi with ubuntu server and container is restarting itself in loop.

Is this image compatible with raspberry pi? If so, than could you please help me debug?

**Comment by JXGA** [comment]
It looks like the images on Docker Hub are linux/amd64, so you probably won't have much success with ARM. The node:latest image which this is based off has an ARM option, so should work if you build your own Docker image. 

I'm not guaranteeing this will work, but what I'd try is below. You can also alter the file `init-and-run-wiki` from this repo with any commands you need to run (closing out issue #4).

- Clone this repo
- On your Pi, go to the folder containing Dockerfile
- Run the command `docker build -t tiddlywiki-arm:v0.1 .` - Include the trailing dot.
- From your docker-compose file or docker run command, change the image to `tiddlywiki-arm:v0.1`, which is stored on the local machine. (`docker run -d -p 8080:8080 tiddlywiki-arm:v0.1`)

Good luck :)

**Comment by m0wer** [comment]
First of all, sorry for the late reply. I didn't get any notifications since the repo is a fork and it was unwatched by default.

The Dockerfile is compatible with RaspberryPi and other ARM based  devices. You can download the ARM image from Docker Hub from now on.
